### ISSUE TITLE
Force disconnect or reset connection

### ISSUE THREAD

**Issue by aharth** [arduino12/ble_rgb_led_strip_controller#1]
Thanks for your re-engineering work, much appreciated!

Do you know of a way to set the device in discoverable mode so that one can connect to (pair) the device? Currently it seems the device remembers the connection without a way to reset and reconnect from another central.

**Comment by arduino12** [comment]
Hi,
The way I remember:
It is always discoverable,
It is pairable if nothing is connected to it - I had no problem switching central device (smartphone, PC, ESP32)...
Make sure you disconnected from the previous central -power it off to be sure :)

**Comment by aharth** [comment]
Ok, will double-check and reopen the bug if the issue on our side should persist. Thanks!
